apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-demo
  namespace: <Name_Space>
spec:
  template:
    metadata:
      labels:
        app: spring-demo
    spec:
      containers:
      - image: heweix86/spring-demo:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: spring-demo
        ports:
        - containerPort: 8000
